In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#installing the CuPy library
!pip install cupy

In [3]:
#importing the library
import numpy as np

In [4]:
#creating a single dimension array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
#creating a multi dimention array
arr_mul = np.array([[1,2,3],[4,5,6]])
arr_mul

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#creating array of complex numbers
arr_com = np.array([1,2,3] , dtype=complex)
arr_com

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#reshaping array

#original shape (4,)
arr = np.array([1,2,3,4])
print("original shape" , arr.shape , arr.ndim)

#reshaping array to be of shape (2,2)
arr.shape = (2,2)
print("reshaped as " , arr.shape , arr.ndim)

# or we can use reshape function as
arr = arr.reshape(4,) #reshape fucntion returns ndarray 
print("shape using reshape" , arr.shape , arr.ndim)

original shape (4,) 1
reshaped as  (2, 2) 2
shape using reshape (4,) 1


In [8]:
#using itemsize for size of each item in an array
arr1= np.array([1,2,3,4,5] , dtype=np.int32)
arr2 = np.array([1,2,3,4,5],dtype = np.float32)
print("itemsize of array 1 is {}, itemsize of array 2 is {}".format(arr1.itemsize , arr2.itemsize))

itemsize of array 1 is 4, itemsize of array 2 is 4


In [9]:
#creating uninitialized array of specified shape and type
arr1 = np.empty([2,3],dtype=np.float32) #create array of size 2*3 with random values
print(arr1)

#creating an array of zeroes
arr2=  np.zeros([2,2])
print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]


In [10]:
#converting python list into CuPy array
lst = [1,2,3,4,5]
arr = np.asarray(lst)
np.resize(arr,(3,2))

#CuPy dont have resize functionality like in numpy
#resize force reshape the array in specified shape by either deleting the array elements or padding zeroes to increase size

array([[1, 2],
       [3, 4],
       [5, 1]])

In [11]:
#iterator in CuPy
x = [1,2,3,4,5]
arr = np.fromiter(x , dtype=np.int32)

#CuPy dont have iterator as in numpy

In [12]:
#generating values between a given range
arr = np.arange(1,10,1,dtype=np.int32)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [13]:
#generating 5 evenly spaced digits using np.linspace
arr = np.linspace(10,20 , num=5)
arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [14]:
#slice from start to end and filter by step of 2
arr = np.arange(10)
arr[2:8:2]

array([2, 4, 6])

In [15]:
#types of slicing:
arr = np.asarray([[1,2,3],[3,4,5],[6,7,8]])
arr[...,0] #print first element of each sub array or extract the first column
arr[...,1] #print second element of each subarray or exxtract the second columm
arr[1,...] #extract the second row
arr[0,...] #extract tge first row
arr[...,1:] #include all rows and exclude 1st colummn

array([[2, 3],
       [4, 5],
       [7, 8]])

In [16]:
#indexing
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
x[[[0,0],[3,3]],[[0,2],[0,2]]]

#using slices
x[1:4,1:3]

#boolean array indexing
x[x>10]

array([11])

In [17]:
#if an array contains NaN values ,  we can omit them using ~isnan , ,here ~ act as not

a = np.array([np.nan , 1,2,3 ,np.nan , 5,6])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6.])

In [18]:
#Broadcasting

"""The term broadcasting refers to the ability of numpy to treat arrays of different shapes during arithmetic operations.

    If the dimensions of two arrays are dissimilar , element to element operations are not possible. However , the operations are still possible using broadcasting
    
    The smaller array is broadcasted to larger array to make its shape compatble to the larger ones"""


a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
b = np.array([10,10,10])
print(a+b)  #b is broadcasted over a

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [19]:
#iterating over an array
a = np.array([1,2,3,4,5,6,7,8,9,10])
a=a.reshape(5,2)
for i in np.nditer(a): #row wise iteration
    print(i)

1
2
3
4
5
6
7
8
9
10


In [20]:
#Transpose using arr.T
print(a)
print(a.T)
print(a.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(5, 2)


In [21]:
#modifying array inplace using op_flags parameter of np.nditer , default value is readonly

for i in np.nditer(a , op_flags=['readwrite']):
    i[...]=i*2
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

# ****Array Manipulation

In [22]:
#Flatten
arr.flatten() 
"""returns the flattend array by combining all the dimensions. Returns a copy"""
#Ravel
arr.ravel() 
"""returns a contiguous flattend array but the copy is only made if needed"""

'returns a contiguous flattend array but the copy is only made if needed'

In [23]:
a =  np.array(np.arange(10)).reshape(5,2)

b = np.array([10,10]).reshape(1,2)
a = np.broadcast(b,a)
print(list(a))
#print(b+a)

[(10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9)]


In [24]:
#broadcast_to(array,shape)
"""This function broadcasts an array to a new shape. It returns a read-only view on the original array. It is typically not contiguous. 
    The function may throw ValueError if the new shape does not comply with NumPy's broadcasting rules."""

import numpy as np 
a = np.arange(4).reshape(1,4) 

print('The original array:' )
print(a) 
print('\n')  

print('After applying the broadcast_to function:') 
print(np.broadcast_to(a,(4,4)))

The original array:
[[0 1 2 3]]


After applying the broadcast_to function:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [30]:
#np.expand_dims(arr,axis)
a = np.array(np.arange(10)).reshape(2,5)
b = np.expand_dims(a , axis=1)
print(b.shape , b.ndim)

(2, 1, 5) 3


In [40]:
#concatenation
"""join two or more arrays along a specified axis"""
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)

In [41]:
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [43]:
print(np.concatenate((a,b),axis=1))

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [ ]:
#same work as stack ,  but stack creates a new axis for second array